name: Check

on:
  push:
    paths-ignore:
      - '**.md'

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Initialization
        uses: ./.github/actions/init
        with:
          jdk: 17

      - name: Detekt check
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: detekt

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Initialization
        uses: ./.github/actions/init
        with:
          jdk: 17

      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build -x test

      - name: Test
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: test
