name: Check

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Initialization
        uses: ./.github/actions/init
        with:
          jdk: 17

      - name: Detekt check
        uses: gradle/gradle-build-action@v2.7.0
        env:
          DETEKT_IGNORE_FAILURES: false
        with:
          arguments: detekt

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Initialization
        uses: ./.github/actions/init
        with:
          jdk: 17

      - name: Build
        uses: gradle/gradle-build-action@v2.7.0
        with:
          arguments: build -x test

      - name: Test
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 10
          command: ./gradlew test
