name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: sonar-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Initialization
        uses: ./.github/actions/init
        with:
          jdk: 17

      - name: Build
        uses: gradle/gradle-build-action@v2.9.0
        env:
          DETEKT_IGNORE_FAILURES: true
        with:
          arguments: build detekt -x test

      - name: Test
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 10
          command: ./gradlew test jacocoTestReport

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
